[package]
name = "virtio-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers" }
netcore = { path = "../netcore" }
